LeetCode/Letter Combination of Phone number/readme.md, LeetCode/Letter Combination of Phone number/solution.cpp
leetcode question in c++ of  Combination of Phone number.
=> solution of leetcode question

LeetCode/Majority Element/readme.md, LeetCode/Majority Element/solution.js
Adding leetcode challenge and solution
=>  leetcode challenge and solution - hacktoberfest

GeeksforGeeks/KadanesAlgo/README.txt, GeeksforGeeks/KadanesAlgo/solution.java
=> added KADANES ALGO GFG

CodeChef/PrimeGame/PrimeGame.java, CodeChef/PrimeGame/readme.md
=> add PrimeGame solution for CodeChef

LeetCode/README.MD, LeetCode/Two Sum/Solution.java, LeetCode/Two Sum/readme.md
=> Added a solution for Two Sum problem from LeetCode using java.

CodeForces/Long Jumps/explanation.md, CodeForces/Long Jumps/readme.md, CodeForces/Long Jumps/solution.cpp
Hey there!
This is Sundar. I'm hereby adding a codeforces problem called "Long Jumps".
Hope you would like it and merge it to Hack-Codes.
=> Adding A Codeforces Problem

LeetCode/Remove duplicates from sorted list/readme.md, LeetCode/Remove duplicates from sorted list/solution.py
For the issue: https://github.com/aritrakrbasu/Hack-Codes/issues/9
=> Leetcode - Remove duplicates from sorted list

GeeksforGeeks/0 - 1 Knapsack/README.txt, GeeksforGeeks/0 - 1 Knapsack/solution.cpp
0-1 Knapsack solution using c++
accepted by GFG
=> 0-1 knapsack Added GFG

LeetCode/Longest Substring Without Repeating Characters/readme.md, LeetCode/Longest Substring Without Repeating Characters/solution.cpp
Please do review the PR. Have added solution for https://leetcode.com/problems/longest-substring-without-repeating-characters/ in C++ (https://github.com/aritrakrbasu/Hack-Codes/issues/9).
=> feat (LeetCode) : add Longest Substring Without Repeating Characters solution

LeetCode/N-th Tribonacci Number/Readme.MD, LeetCode/N-th Tribonacci Number/Solution.java
Hey there! Here's my first contribution towards Hacktober Fest 2021. Hope it gets accepted!
=> Solution with Recursion

LeetCode/Find Numbers with Even Number of Digits/README.MD, LeetCode/Find Numbers with Even Number of Digits/Solution.java, LeetCode/N-th Tribonacci Number/Readme.MD, LeetCode/N-th Tribonacci Number/Solution.java
=> Find Numbers with even numbers

LeetCode/Find Numbers with Even Number of Digits/README.MD, LeetCode/Find Numbers with Even Number of Digits/Solution.java, LeetCode/Longest Turbulent Subarray/Readme.MD, LeetCode/Longest Turbulent Subarray/Solution.java, LeetCode/N-th Tribonacci Number/Readme.MD, LeetCode/N-th Tribonacci Number/Solution.java
Here's my third *brilliant* contribution! XD
=> Longest Turbulent Subarray

LeetCode/Tree Level Order Traversal/readme.md, LeetCode/Tree Level Order Traversal/solution.cpp
I have added tree level order traversal solution code in C++ and also added the details in the readme file.
I hope you will like it.
Thank you.
=> Tree level order traversal added

LeetCode/Find Numbers with Even Number of Digits/README.MD, LeetCode/Find Numbers with Even Number of Digits/Solution.java, LeetCode/Longest Turbulent Subarray/Readme.MD, LeetCode/Longest Turbulent Subarray/Solution.java, LeetCode/N-th Tribonacci Number/Readme.MD, LeetCode/N-th Tribonacci Number/Solution.java, LeetCode/Reverse Only Letters/README.MD, LeetCode/Reverse Only Letters/Solution.java
=> Reverse Only Letters

HackerRank/Class vs. Instance/README.MD, HackerRank/Class vs. Instance/Solution.java, LeetCode/Find Numbers with Even Number of Digits/README.MD, LeetCode/Find Numbers with Even Number of Digits/Solution.java, LeetCode/Longest Turbulent Subarray/Readme.MD, LeetCode/Longest Turbulent Subarray/Solution.java, LeetCode/N-th Tribonacci Number/Readme.MD, LeetCode/N-th Tribonacci Number/Solution.java, LeetCode/Reverse Only Letters/README.MD, LeetCode/Reverse Only Letters/Solution.java
=> Day 4:Class vs. Instance

LeetCode/Multiply Strings/readme.md, LeetCode/Multiply Strings/solution.cs
My solution for Leetcode Multiply Strings problem
Resolves #9
=> Resolves #9: Multiply Strings

Others/multiple_inharitance_reportcard_question/readme.md, Others/multiple_inharitance_reportcard_question/solution.cpp
if i am doing this the right way please tell me @aryankambozz@gmail.com i am complete noob with github
=> Add files via upload ;;i have no idea whats going on somone help me out plzz with making these pull requests and all hacktoberfest-accepted 

GeeksforGeeks/Hamiltonian_Path/README.md, GeeksforGeeks/Hamiltonian_Path/soultion.cpp
Added my cpp solution of hamiltonian path gfg question.
=> Hamiltonian Path

LeetCode/TextPalindrome/Palindrome.cpp, LeetCode/TextPalindrome/README.MD, LeetCode/TextPalindrome/solution.cpp
Added a Leetcode Problem written in C++ Language also with a readme file with explanation how the code works.
=> Added Valid Palindrome Leetcode Question #125 solution

CodeChef/Magical Doors/readme.md, CodeChef/Magical Doors/solution.cpp
Here I have given the solution of the Codechef Magical Doors question with proper comments.
Please Merge my request.
=> added CodeChef Magical Doors

HackerRank/Boxes through a Tunnel/readme.md, HackerRank/Boxes through a Tunnel/solution.c
I'm the 33rd fork-er of your repo
merge my PR (pleaze)😬
=> Added a HackerRank solution

HackerRank/Caesar Cipher/README.md, HackerRank/Caesar Cipher/solution.cpp, HackerRank/CamelCase/README.md, HackerRank/CamelCase/Solution.cpp
PR for Hakerrank's Caesar Cipher Problem.
=> Hack-Codes:HackerRank:Caesar Cipher

LeetCode/Find_Peak_Element/explanation.md, LeetCode/Find_Peak_Element/readme.md, LeetCode/Find_Peak_Element/solution.py
Hi I've added the leetcode problem Find Peak Element.
Although I'm a bit confused with the folder naming. Please do let me know if the folder name needs to be updated. (Removing "_" from the name).
Thanks.
=> Added Leetcode Problem: Find Peak Element

GeeksforGeeks/Binary Tree to DLL/readme.md, GeeksforGeeks/Binary Tree to DLL/solution.cpp
This is my contribution to the repository. I've added the Binary Tree to DLL problem in the GeeksforGeeks folder.
Let me know if it requires any updates.
You can confirm the solution is originally by me through my  profile https://auth.geeksforgeeks.org/user/sanketmathur/practice/
=> Added GeeksforGeeks Problem: Binary Tree to DLL

LeetCode/Count_sub_islands/README.md, LeetCode/Count_sub_islands/solution.cpp
Please accept this under hacktoberfest
=> Added solution to Count sub islands problem

LeetCode/Word Ladder/readme.md, LeetCode/Word Ladder/solution.cpp
LEETCODE Question No 127 Level: Hard
#hacktoberfest
=> Added Word Ladder Problem with Solution in C++

LeetCode/Valid Sudoku/validsoduko.cpp
=>  valid -Sudoku

HackerRank/Diagonal Difference/readme.md, HackerRank/Diagonal Difference/solution.ts
This PR adds a typescript solution for the Diagonal Difference problem from HackerRank ([link](https://www.hackerrank.com/challenges/diagonal-difference/problem)). I also tried to improve the README for this problem.
=> Solved Diagonal Difference HackerRank problem

LeetCode/zig_zag_conversion/README.md, LeetCode/zig_zag_conversion/zig_zag.cpp
I have tested the following question on various coding platforms on edge and boundary test cases.
=> Zig Zag Conversion 

HackerRank/Queue using Two Stacks/readme.md, HackerRank/Queue using Two Stacks/solution.c
This PR adds a C solution for the Queue using Two Stacks problem from HackerRank ([link](https://www.hackerrank.com/challenges/queue-using-two-stacks/problem))
=> Solved Queue using Two Stacks HackerRank problem

Others/book shop.cpp
=> book shop in c++

HackerRank/Couting Valleys/readme.md, HackerRank/Couting Valleys/solution.c
This PR adds a C solution for the Couting Valleys problem from HackerRank ([link](https://www.hackerrank.com/challenges/counting-valleys/problem))
=> Solved Couting Valleys HackerRank problem
